---

  - name: set ec2 pod specification
    set_fact:
        ec2_pod_spec:
            key: gobig
            rules:
              - proto: all
                from_port: all
                to_port: all
                group_name: ec2_pod_gobig-benchmark-7

              - proto: tcp # ssh
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0

            name: gobig-benchmark-7

            hosts:
                computenode:
                    name: cn-7
                    count: 3
                    type: m4.4xlarge
                    groups:
                      - masters
                      - slaves
                      - datanodes
                      - zookeepers
                      - spark
                      - benchmark
                    volumes:
                        sdb: 50
                        sdc: 1000

                computenode-slaves-only:
                    name: cn-7
                    count: 4
                    type: m4.4xlarge
                    groups:
                      - slaves
                      - datanodes
                      - spark
                      - benchmark
                    volumes:
                        sdb: 50
                        sdc: 1000

                headnode:
                    name: nn-7
                    type: t2.medium
                    groups:
                      - namenodes
                      - clients
                      - spark
                      - headnode
                      - benchmark
                    volumes:
                        sdb: 10
                        sdc: 50

